### ISSUE TITLE
Describe config vars

### ISSUE THREAD

**Issue by trufae** [radareorg/r2yara#39]
this shoudlnt be empty

```
[0x100003a58]> e??~yara
         yara.amount:
         yara.author:
           yara.date:
    yara.description:
           yara.rule:
           yara.tags:
        yara.version:
[0x100003a58]>
```
